# cluster local: as portas do host apontam para os NodePorts do cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: biblioteca
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # api-gateway
        hostPort: 8000
      - containerPort: 30300 # grafana
        hostPort: 3000
      - containerPort: 30411 # zipkin
        hostPort: 9411
      - containerPort: 31672 # painel do rabbitmq
        hostPort: 15672
